AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS CI/CD Pipeline for Static Website Hosting"

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private